# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=5000)),
                ('ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
