name: Production build

on:
  push:
    branches:
      - master
      - feature/docker
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      IMAGE_NAME: website
      REGISTRY_URL: docker.pkg.github.com/damienallen/website/flask
      TAG: master

    steps:
      - uses: actions/checkout@v3
      - name: Checkout repo with submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Build docker container
        run: |
          docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          docker pull $REGISTRY_URL:$TAG || true
          docker build -t $IMAGE_NAME:$TAG --cache-from $REGISTRY_URL:$TAG --target production_build -f docker/Dockerfile .
          docker tag $IMAGE_NAME:$TAG $REGISTRY_URL:$TAG
          docker push $REGISTRY_URL:$TAG
